// Bilingual strings for the DDP Player pages (/ddp/ and /pt/ddp/).
module.exports = {
  en: {
    lang: "en",
    studioUrl: "https://knurlmastering.com/en/",
    altUrl: "https://knurlmastering.com/pt/ddp/",
    canonical: "https://knurlmastering.com/en/ddp/",
    ogLocale: "en_GB",
    title: "Free Online DDP Player — Play & Verify CD Masters | Knurl Mastering",
    description: "A free, private, in-browser DDP player. Load a DDP fileset to audition your CD master, step through the tracklist and read PQ codes, ISRC, UPC/EAN and CD-Text. Nothing is uploaded — by Knurl Mastering.",
    ogTitle: "Free Online DDP Player — Knurl Mastering",
    ogDescription: "Play and verify a DDP CD master in your browser. PQ, ISRC, UPC and CD-Text. Free and private — nothing is uploaded.",
    studioBack: "← Studio",
    h1Pre: "DDP",
    h1Accent: "Player",
    intro1: "A free web app — nothing to install. Load a DDP fileset to audition the master, step through the tracklist, and read the PQ codes, ISRC, UPC/EAN and CD-Text.",
    intro2: "Everything runs in your browser — your files are never uploaded. Free for everyone.",
    dzTitle: "Drop a DDP folder, its files, or a .zip here",
    dzOr: "or choose below",
    chooseFolder: "Choose DDP",
    chooseFiles: "Choose DDP",
    dzHintPre: "Expects the usual DDP set:",
    dzHintPost: "the audio image (.DAT) and optional CDTEXT.BIN.",
    exportBtn: "Download PQ sheet",
    loadAnother: "Load another",
    tracklist: "Tracklist",
    waveformLabel: "Waveform. Click or drag to seek.",
    footerBuilt: "Built by Knurl Mastering using AI/LLM coding tools.",
    footerStudioLink: "Knurl Mastering",
    footerFree: "Free & private. DDP is a trademark of DCA, Inc.",
    seoH2: "A free, private DDP player",
    seoBody: [
      "A <strong>DDP image</strong> (Disc Description Protocol) is the master format CD pressing plants use to manufacture an audio CD. It carries the audio together with the PQ subcode — track start times, pre-gaps, ISRC codes, the UPC/EAN barcode and CD-Text. This player lets you open a DDP fileset and confirm everything is correct <em>before</em> it goes to manufacturing.",
      "It runs entirely in your browser. Your master never leaves your computer — nothing is uploaded to any server — so it is safe to use with unreleased material."
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is a DDP file?", a: "A DDP (Disc Description Protocol) fileset is the standard delivery format for a finished CD master. It usually contains a DDPID, DDPMS and PQDESCR descriptor, the audio image (a .DAT file) and an optional CDTEXT.BIN. Pressing plants use it to manufacture the disc exactly as the mastering engineer intended." },
      { q: "Is this DDP player really free?", a: "Yes — it is completely free, with no sign-up. We built it for the community and for our own clients at Knurl Mastering, so anyone can audition and verify a DDP master." },
      { q: "Are my files uploaded anywhere?", a: "No. The player reads and decodes your DDP entirely inside your browser using the Web Audio API. Nothing is sent to a server, which makes it safe for unreleased records." },
      { q: "What can I check with it?", a: "Track titles and performers (CD-Text), track start times and durations, pre-gaps, ISRC codes per track, the UPC/EAN barcode, the DDP level and the total programme time. You can also play the audio and export a PQ sheet." },
      { q: "Which DDP versions are supported?", a: "Red Book audio DDP 2.00 and 1.01 — the versions used for audio CD manufacturing. CD-Text is read when present." }
    ],
    contactUrl: "https://knurlmastering.com/en/#contact",
    bugText: "Found a bug?",
    bugLink: "Get in touch"
  },

  pt: {
    lang: "pt",
    studioUrl: "https://knurlmastering.com/pt/",
    altUrl: "https://knurlmastering.com/en/ddp/",
    canonical: "https://knurlmastering.com/pt/ddp/",
    ogLocale: "pt_PT",
    title: "Leitor de DDP online grátis: ouça e verifique masters de CD | Knurl Mastering",
    description: "Um leitor de DDP gratuito e privado, que corre no seu navegador. Carregue um conjunto DDP para ouvir o master de CD, percorrer o alinhamento e ver os códigos PQ, ISRC, UPC/EAN e o CD-Text. Nada é enviado para servidores. Um projeto da Knurl Mastering.",
    ogTitle: "Leitor de DDP online grátis | Knurl Mastering",
    ogDescription: "Ouça e verifique um master de CD em DDP no seu navegador. PQ, ISRC, UPC e CD-Text. Gratuito e privado, sem enviar nada para lado nenhum.",
    studioBack: "← Estúdio",
    h1Pre: "Leitor",
    h1Accent: "DDP",
    intro1: "Uma aplicação web gratuita, sem necessidade de instalação. Carregue um conjunto DDP para ouvir o master, percorrer o alinhamento e ver os códigos PQ, ISRC, UPC/EAN e o CD-Text.",
    intro2: "Tudo acontece no seu navegador e os seus ficheiros nunca saem do computador. É gratuito para toda a gente.",
    dzTitle: "Arraste para aqui uma pasta DDP, os seus ficheiros ou um .zip",
    dzOr: "ou escolha em baixo",
    chooseFolder: "Escolher DDP",
    chooseFiles: "Escolher DDP",
    dzHintPre: "Precisa do conjunto DDP habitual:",
    dzHintPost: "a imagem de áudio (.DAT) e, se existir, o CDTEXT.BIN.",
    exportBtn: "Descarregar folha PQ",
    loadAnother: "Carregar outro",
    tracklist: "Alinhamento",
    waveformLabel: "Forma de onda. Clique ou arraste para mover.",
    footerBuilt: "Feito pela Knurl Mastering com ferramentas de IA/LLM.",
    footerStudioLink: "Knurl Mastering",
    footerFree: "Gratuito e privado. DDP é uma marca registada da DCA, Inc.",
    contactUrl: "https://knurlmastering.com/pt/#contact",
    bugText: "Encontrou algum erro?",
    bugLink: "Fale connosco",
    seoH2: "Um leitor de DDP gratuito e privado",
    seoBody: [
      "Uma <strong>imagem DDP</strong> (Disc Description Protocol) é o formato de master que as fábricas usam para produzir um CD áudio. Junta o áudio ao subcódigo PQ, ou seja, os tempos de início das faixas, os pré-gaps, os códigos ISRC, o código de barras UPC/EAN e o CD-Text. Com este leitor pode abrir um conjunto DDP e confirmar que está tudo certo <em>antes</em> de o disco seguir para fabrico.",
      "Corre por inteiro no seu navegador. O seu master nunca sai do computador e nada é enviado para nenhum servidor, por isso pode usá-lo à vontade com material ainda inédito."
    ],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "O que é um ficheiro DDP?", a: "Um conjunto DDP (Disc Description Protocol) é a forma habitual de entregar um master de CD terminado. Costuma incluir os descritores DDPID, DDPMS e PQDESCR, a imagem de áudio (um ficheiro .DAT) e, quando existe, o CDTEXT.BIN. É com ele que as fábricas produzem o disco tal como o engenheiro de masterização o deixou." },
      { q: "Este leitor de DDP é mesmo grátis?", a: "É, sim. É totalmente gratuito e não precisa de registo. Fizemo-lo para a comunidade e para os nossos clientes na Knurl Mastering, para que qualquer pessoa possa ouvir e verificar um master DDP." },
      { q: "Os meus ficheiros vão para algum lado?", a: "Não vão. O leitor lê e descodifica o DDP inteiramente dentro do navegador, com a Web Audio API. Não há nada a enviar para servidores, por isso é seguro usar com discos ainda inéditos." },
      { q: "O que posso verificar?", a: "Os títulos e intérpretes das faixas (CD-Text), os tempos de início e as durações, os pré-gaps, os códigos ISRC de cada faixa, o código de barras UPC/EAN, o nível de DDP e a duração total do programa. Pode também ouvir o áudio e exportar uma folha PQ." },
      { q: "Que versões de DDP funcionam?", a: "As de áudio Red Book, DDP 2.00 e 1.01, que são as usadas no fabrico de CD áudio. Quando o CD-Text está presente, também é lido." }
    ]
  }
};
